export const MOBILE_BREAKPOINT = 480;
export const MOBILE_TABLET_BREAKPOINT = 600;
export const TABLET_BREAKPOINT = 768;
export const SMALL_SCREEN_BREAKPOINT = 1024;
export const MEDIUM_SCREEN_BREAKPOINT = 1280;
export const LARGE_SCREEN_BREAKPOINT = 1440;
